### ISSUE TITLE
wishlist: ability to change blogpost creation date via admin

### ISSUE THREAD

**Issue by debalance** [jabber-at/hp#15]
I would like the ability to change a blogpost's creation date through /admin/ because it is displayed above the blogpost on the website.

**Comment by mathiasertl** [comment]
This was a bit more tricky, because the "created" field is set in the base model and has ``auto_now_add=True``. This means that the Django ORM won't allow you to modify that field. The actual idea of the field is to always have a timestamp of when an object was created, hence the name. 

The new field ``publication_date`` has ``default=timezone.now``, which is the same in default behavior ("set it to now, when object is created"), but can be edited in the admin interface. 

As an added bonus, you can also set a publication date in the future to automatically publish a post at that point in time.
